# -*- coding: utf-8 -*-
"""app1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l3zqzWiNMBfNf2Nwokm7EndBb_FWr2cm
"""

import numpy as np
from flask import Flask, request, jsonify
import pickle

#Load the machine learning model
import firebase_admin
from firebase_admin import credentials, db
from flask import Flask, request, jsonify
import pickle
import sklearn



# Load the machine learning model
with open('model (6) (2).pkl', 'rb') as f:
    model = pickle.load(f)
# prediction = model.predict(np.array([[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]]))
# Initialize the Firebase app
cred = credentials.Certificate("msensors-firebase-adminsdk-bxjxx-9307ca3f6d.json")
firebase_admin.initialize_app(cred, {
    'databaseURL': 'https://msensors-default-rtdb.firebaseio.com/'
})

# Create a Flask app
app = Flask(__name__)


# Define a route to handle requests

@app.route('/', methods=['GET', 'POST'])
def predict():
    ref = db.reference('/sensors')
    sensoerdata = ref.get()

    features = [
        sensoerdata['id'],
        sensoerdata['pressure'],
        sensoerdata['humidity'],
        sensoerdata['winddirDegree'],
        sensoerdata['windspeedKmph'],
        sensoerdata['mintempC'],
        sensoerdata['maxtempC'],
        sensoerdata['temperature'],
        sensoerdata['ppm'],
        sensoerdata['pm'],
    ]

    # Extract the dictionary from the list

    prediction = model.predict([features])


    predictions = ['Good', 'Moderate', 'Unhealthy for sensitive groups', 'Unhealthy', 'Very unhealthy',
                   'Hazardous']  # Replace with your actual predictions
    output_ref = db.reference('/modeloutput')
    output_ref.set((prediction[0]))
    # Return the prediction as a response
    return jsonify({'prediction': prediction[0]})



# Run the app
if __name__ == '__main__':
    app.run(debug=True)
